(define (problem Ejercicio1)
	(:domain Belkan)
	(:OBJECTS 
		Princesa Principe Bruja Profesor DiCaprio - NPC
		Oscar Manzana Rosa Algoritmo Oro - Item
		Jugador - Player
		Map1 Map2 Map3 Map4 Map5 Map6 Map7 Map8 Map9 Map10 Map11 Map12 Map13 Map14 Map15 Map16 Map17 Map18 Map19 Map20 Map21 Map22 Map23 Map24 Map25 - Zone
		Norte Sur Este Oeste - Orientation
	)
	(:INIT
		(Conection Map1 Map2 Este)
		(Conection Map2 Map1 Oeste)
		(Conection Map2 Map3 Este)
		(Conection Map3 Map2 Oeste)
		(Conection Map3 Map4 Este)
		(Conection Map4 Map3 Oeste)
		(Conection Map4 Map5 Este)
		(Conection Map5 Map4 Oeste)
		(Conection Map1 Map6 Sur)
		(Conection Map6 Map1 Norte)
		(Conection Map6 Map11 Sur)
		(Conection Map11 Map6 Norte)
		(Conection Map11 Map16 Sur)
		(Conection Map16 Map11 Norte)
		(Conection Map21 Map16 Sur)
		(Conection Map16 Map21 Norte)
		(Conection Map5 Map10 Sur)
		(Conection Map10 Map5 Norte)
		(Conection Map10 Map15 Sur)
		(Conection Map15 Map10 Norte)
		(Conection Map15 Map20 Sur)
		(Conection Map20 Map15 Norte)
		(Conection Map20 Map25 Sur)
		(Conection Map25 Map20 Norte)
		(Conection Map21 Map22 Este)
		(Conection Map22 Map21 Oeste)
		(Conection Map22 Map23 Este)
		(Conection Map23 Map22 Oeste)
		(Conection Map23 Map24 Este)
		(Conection Map24 Map23 Oeste)
		(Conection Map24 Map25 Este)
		(Conection Map25 Map24 Oeste)
		(Conection Map3 Map8 Sur)
		(Conection Map8 Map3 Norte)
		(Conection Map8 Map13 Sur)
		(Conection Map13 Map8 Norte)
		(Conection Map13 Map18 Sur)
		(Conection Map18 Map13 Norte)
		(Conection Map18 Map23 Sur)
		(Conection Map23 Map18 Norte)
		(Conection Map11 Map12 Este)
		(Conection Map12 Map11 Oeste)
		(Conection Map12 Map13 Este)
		(Conection Map13 Map12 Oeste)
		(Conection Map13 Map14 Este)
		(Conection Map14 Map13 Oeste)
		(Conection Map14 Map15 Este)
		(Conection Map15 Map14 Oeste)
		(Conection Map7 Map12 Sur)
		(Conection Map12 Map7 Norte)
		(Conection Map12 Map17 Sur)
		(Conection Map17 Map12 Norte)
		(Conection Map9 Map14 Sur)
		(Conection Map14 Map9 Norte)
		(Conection Map14 Map19 Sur)
		(Conection Map19 Map14 Norte)
		(PositionItem Oscar Map7)
		(PositionItem Manzana Map17)
		(PositionItem Rosa Map9)
		(PositionItem Algoritmo Map19)
		(PositionItem Oro Map11)
		(PositionNPC Princesa Map1)
		(PositionNPC Principe Map5)
		(PositionNPC Bruja Map15)
		(PositionNPC Profesor Map21)
		(PositionNPC DiCaprio Map25)
		(PositionPlayer Jugador Map13)
		(OrientationPlayer Norte)
		(EmptyHand)
	)
	(:goal 
		(and (Has Oscar DiCaprio) (Has Rosa Princesa) (Has Manzana Bruja) (Has Algoritmo Profesor))
	)
)